name: polkawallet_plugin_xxnetwork
description: The xxnetwork network flutter plugin for polkawallet app.
version: 0.3.0
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  charts_flutter: ^0.10.0
  http: ^0.13.0
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  flutter_svg: ^0.22.0
  get_storage: ^2.0.2
  json_annotation: ^4.0.1
  polkawallet_sdk: ^0.3.2
  # polkawallet_sdk:
  #   path: ../sdk
  polkawallet_ui:
    git:
      url: https://github.com/polkawallet-io/ui.git
      ref: 485a9cde97f2446d74a1aeb6d8d63e33683461a5
    # path: ../ui

dev_dependencies:
  build_runner: ^2.0.3
  mobx_codegen: ^2.0.1+3
  json_serializable: ^4.1.2
  flutter_test:
    sdk: flutter

dependency_overrides:
 polkawallet_ui:
   path: ../ui
 polkawallet_sdk:
   path: ../sdk

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/public/bg_protonet.png
    - assets/images/public/bg_xxnetwork.png
    - assets/images/public/protonet.png
    - assets/images/public/protonet_gray.png
    - assets/images/public/xxnetwork.png
    - assets/images/public/xxnetwork_gray.png
    - assets/images/public/staking.png
    - assets/images/public/staking_black.png
    - assets/images/public/staking_pink.png
    - assets/images/public/governance.png
    - assets/images/public/governance_black.png
    - assets/images/public/governance_pink.png
    - assets/images/staking/ok.svg
    - assets/images/staking/error.svg
    - assets/images/staking/reward.svg
    - assets/images/staking/slash.svg
    - assets/images/gov/democracy.svg
    - assets/images/gov/council.svg
    - assets/images/gov/treasury.svg
    - assets/images/tokens/KSM.png
    - assets/images/tokens/DOT.png
    - assets/images/public/polkassembly.png
    - assets/images/public/nav_staking.svg
    - assets/images/public/nav_governance.svg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
